logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: DEBUG

spring:
  profiles:
    active:
      - local
      - common
    group:
      local:
        - db-local
        - security-local
      prob:
        - db-prod
        - security-prod
    include:
      - db
      - security
